// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trabalho;

#nullable disable

namespace CarAdmin.Migrations
{
    [DbContext(typeof(BaseRentCar))]
    [Migration("20221010170146_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Trabalho.Carro", b =>
                {
                    b.Property<int>("idCarro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("modelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("placa")
                        .HasColumnType("TEXT");

                    b.ToTable("Carro");
                });

            modelBuilder.Entity("Trabalho.Cliente", b =>
                {
                    b.Property<int>("contato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<int>("idCliente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Trabalho.Emprestimo", b =>
                {
                    b.Property<string>("datadev")
                        .HasColumnType("TEXT");

                    b.Property<string>("dataempr")
                        .HasColumnType("TEXT");

                    b.Property<int>("idCarro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idVendedor")
                        .HasColumnType("INTEGER");

                    b.ToTable("Emprestimo");
                });

            modelBuilder.Entity("Trabalho.Vendedor", b =>
                {
                    b.Property<int>("idVendedor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomeFuncionario")
                        .HasColumnType("TEXT");

                    b.ToTable("Vendedor");
                });
#pragma warning restore 612, 618
        }
    }
}
